accepted = [
    "ISC",
    "Zlib",
    "0BSD",
    "Unlicense",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "AGPL-3.0",
    "NOASSERTION",
    "GPL-2.0",
    "LGPL-2.1",
    "MPL-2.0",
    "OpenSSL"
]
