[workspace]
resolver = "2"
members = [
    "mgba",
    "tango",
    "tango-protos",
    "tango-server",
    "datachannel-wrapper",
    "hqx",
    "mmpx",
    "input-helper",
]

[patch.crates-io]
sdl2 = { git = "https://github.com/tangobattle/rust-sdl2", rev = "c006781b6293115d1b5f361da093894a1cf0a7eb" }
egui = { git = "https://github.com/emilk/egui", rev = "1fe08bf7e4bf845b8cb0a677a206e61d1744eb73" }
wgpu = { git = "https://github.com/tangobattle/wgpu", rev = "ba9a49aa0b4cad4a1b52e47b1d94f572947d076b" }
