[workspace]
resolver = "2"
members = [
    "mgba",
    "tango",
    "tango-dataview",
    "tango-protos",
    "tango-server",
    "datachannel-wrapper",
    "hqx",
    "mmpx",
    "input-helper",
    "bps",
]

[patch.crates-io]
sdl2 = { git = "https://github.com/tangobattle/rust-sdl2", rev = "08bbc3d47cdccc0620373b73f2f1c1a5299d3f43" }
