[package]
name = "mgba-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
libz-sys = { version = "1.1.0", default-features = false, features = ["libc"] }

[build-dependencies]
bindgen = "0.57"
cmake = "0.1"
shell-words = "1.1"
