[package]
name = "mgba"
version = "4.0.32"
edition = "2021"

[dependencies]
anyhow = "1"
const-zero = "0.1"
lazy_static = "1.4"
log = "0.4"
mgba-sys = { path = "mgba-sys" }
parking_lot = "0.12"
send_wrapper = "0.5"

[build-dependencies]
bindgen = "0.57"
cmake = "0.1"
