[workspace]
resolver = "2"
members = [
    "mgba",
    "tango-core",
    "tango-protos",
    "tango-server",
    "mgba-sys",
    "keymaptool",
    "datachannel-wrapper",
]

[patch.crates-io]
glium = { git = "https://github.com/bigfarts/glium", rev = "27cf5774e076a8aa5ef02ddb00ad836dfef41859" }
