[workspace]
resolver = "2"
members = [
    "mgba",
    "tango-core",
    "tango-signaling",
    "tango-protos",
    "mgba-sys",
    "keymaptool",
    "datachannel-wrapper",
]

[patch.crates-io]
datachannel = { git = "https://github.com/bigfarts/datachannel-rs", rev = "7071a240e734a99be0697b777ce367b668b85ec0" }
