[package]
name = "tango-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
anyhow = "1.0"
env_logger = "0.9.0"
log = "0.4"
futures-util = "0.3.21"
envconfig = "0.10.0"
git-version = "0.3.5"
datachannel-wrapper = { path = "../datachannel-wrapper" }
tango-protos = { path = "../tango-protos" }
prost = "0.10"
bytes = "1.1.0"
hyper = "0.14"
hyper-tungstenite = "0.8"
routerify = "3.0"
tungstenite = "0.17"
rand = "0.8"
