[package]
name = "tango-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = { version = "0.17.1", features = ["native-tls"] }
tokio = { version = "1.15.0", features = ["full"] }
anyhow = "1.0"
env_logger = "0.9.0"
log = "0.4"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
futures-util = "0.3.21"
envconfig = "0.10.0"
git-version = "0.3.5"
datachannel-wrapper = { path = "../datachannel-wrapper" }
tango-protos = { path = "../tango-protos" }
prost = "0.10"
bytes = "1.1.0"
hyper = "0.14"
hyper-tungstenite = "0.8"
routerify = "3.0"
