[package]
name = "tango-dataview"
version = "4.0.45"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
byteorder = "1.4.3"
thiserror = "1.0"
image = "0.24"
parking_lot = "0.12.0"
ndarray = "0.15"
