[package]
name = "nettai-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
hyper = "0.14"
hyper-tungstenite = "0.8"
log = "0.4"
once_cell = "1"
routerify = "3"
semver = "1"
tokio = { version = "1", features = ["full"] }
tungstenite = "0.17"
