name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: win32-x64

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine-stable wine64 wine32:i386 wine64

      - run: npm install && npm run build

      - run: GITHUB_TOKEN="${{ secrets.github_token }}" npm run "dist:${{ matrix.target }}"" --publish always
