name: release

on:
    release:
        types:
            - created

jobs:
    release-win32-x64:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - uses: pat-s/always-upload-cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      core/target
                  key: win32-x64-cargo-${{ hashFiles('**/Cargo.lock') }}

            - run: >
                  sudo apt install -y msitools mingw-w64 imagemagick wget

            - run: >
                  sudo pip3 install semver==3.0.0-dev3 toml

            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  targets: x86_64-pc-windows-gnu

            - run: >
                  sudo update-alternatives --quiet --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-win32 60 &&
                  sudo update-alternatives --quiet --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix 90 &&
                  sudo update-alternatives --quiet --config x86_64-w64-mingw32-gcc &&
                  sudo update-alternatives --quiet --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-win32 60 &&
                  sudo update-alternatives --quiet --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 90 &&
                  sudo update-alternatives --quiet --config x86_64-w64-mingw32-g++

            - run: >
                  BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/usr/x86_64-w64-mingw32/" ./win/build.sh

            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./dist/tango-x86_64-windows.msi
                  asset_name: tango-${{ github.ref_name }}-x86_64-windows.msi
                  asset_content_type: application/octet-stream

    release-mac-universal:
        runs-on: macos-12

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - uses: pat-s/always-upload-cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      core/target
                  key: darwin-universal-cargo-${{ hashFiles('**/Cargo.lock') }}

            - run: >
                  sudo pip3 install semver==3.0.0-dev3 toml

            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  targets: x86_64-apple-darwin, aarch64-apple-darwin

            - run: >
                  ./macos/build.sh

            - uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./dist/tango-macos.zip
                  asset_name: tango-${{ github.ref_name }}-macos.zip
                  asset_content_type: application/zip
